- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: hooks/helmlint.sh
  language: script
  files: \.((ya?ml)|(tpl))$
  require_serial: true

- id: helm-unittest
  name: helm-unittest
  description: Run helm unittest
  entry: hooks/helm-unittest.sh
  language: script
  files: \.((ya?ml)|(tpl))$
  require_serial: true

- id: helm-kuttl
  name: helm-kuttl
  description: Run kuttl tests
  entry: hooks/helm-kuttl.sh
  language: script
  files: \.((ya?ml)|(tpl))$
  require_serial: true
